# Generated by Django 5.2 on 2025-04-16 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74067c93-8301-4db1-a79b-57b39955733f'), primary_key=True, serialize=False),
        ),
    ]
